<br /><br />
<div id="view-content">
	<p>View script for controller <b>Country</b> and script/action name <b>index</b></p>
	
	Country Entries: <br />
	
	<dl>
		<?php foreach ($this->countries as $country): ?>
		<dt><?php echo $this->escape($country->Name).' '.$this->escape($country->Code); ?> </dt>
		
		<dd><?php echo $this->escape($country->Continent); ?> </dd>
		<dd><?php echo $this->escape($country->Region); ?> </dd>
		<dd><?php echo $this->escape($country->SurfaceArea); ?> </dd>
		<?php endforeach ?>
	</dl>
	
	
</div>